apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-eks
  region: us-east-1

iam:
  withOIDC: true
  serviceRoleARN: arn:aws:iam::993051104393:role/EKSClusterRole
  
managedNodeGroups: # Or use 'nodeGroups' for unmanaged
  - name: al23-managed-ng
    instanceType: t3.medium
    desiredCapacity: 1
    iam:
      instanceRoleARN: arn:aws:iam::993051104393:role/EKSNodeRole
    # 🌟 KEY SETTING: Use the amiFamily property to specify AL2023 🌟
    amiFamily: AmazonLinux2023