version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8081:80"
    restart: always #Ensure that the container restarts automatically if it stops.


# bind volumes
version: '3'
services:
  nginx1:
    image: nginx
    ports:
      - "8081:80"
    restart: always
    networks:
      hulk:
        ipv4_address: 192.168.0.4
    volumes:
    #  Bind mount
      - ./html:/usr/share/nginx/html
  nginx2:
    image: nginx
    ports:
      - "8082:80"
    restart: always
    networks:
      hulk:
        ipv4_address: 192.168.0.5
    volumes:    
      # Named Volumes  
      - Nginx_Vol:/usr/share/nginx/html
networks:
  hulk:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/26

volumes:
  Nginx_Vol:



# word press docker compose
# ------------------------
      

